const KEY='oravena_demo_system_v3';
const $=s=>document.querySelector(s),esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const uid=(p='x')=>p+'-'+Date.now().toString(36)+Math.random().toString(36).slice(2,6),today=()=>new Date().toISOString().slice(0,10),now=()=>new Date().toLocaleString('ar-EG');
const allSections=['dashboard','appointments','patients','sessions','odontogram','plans','prescriptions','imaging','finance','inventory','labs','staff','messages','reports','audit','settings'];
const sectionLabels={dashboard:'لوحة المتابعة',appointments:'المواعيد',patients:'المرضى والعملاء',sessions:'الجلسات',odontogram:'خريطة الأسنان 3D',plans:'خطط العلاج',prescriptions:'الوصفات',imaging:'الصور والأشعة',finance:'الحسابات',inventory:'المخزون',labs:'المعامل',staff:'المستخدمون والصلاحيات',messages:'الرسائل',reports:'التقارير',audit:'سجل العمليات',settings:'الإعدادات'};
const sectionIcons={dashboard:'⌂',appointments:'◷',patients:'♙',sessions:'✚',odontogram:'◉',plans:'☷',prescriptions:'Rx',imaging:'▣',finance:'₺',inventory:'▤',labs:'⚗',staff:'♟',messages:'✉',reports:'▥',audit:'⌁',settings:'⚙'};
const permissionTemplates={'الدكتور':['dashboard','appointments','patients','sessions','odontogram','plans','prescriptions','imaging','messages'],'الاستقبال':['dashboard','appointments','patients','messages'],'الحسابات':['dashboard','patients','finance','reports'],'المخزون والمعامل':['dashboard','inventory','labs','reports']};
const blankTeeth=()=>Object.fromEntries(Array.from({length:32},(_,i)=>[i+1,{status:'healthy',stage:'',needs:'',note:''}]));
function demoSeed(){return{
 appointments:[{id:'a1',patientId:'p1',patient:'سارة محمد',phone:'+90 555 120 2244',doctor:'د. أحمد سامي',service:'متابعة علاج',date:'2026-09-08',time:'10:30',status:'مؤكد',changeReason:''},{id:'a2',patientId:'p2',patient:'عمر خالد',phone:'+90 555 771 3900',doctor:'د. ليلى مراد',service:'فحص وتشخيص',date:'',time:'',status:'طلب جديد',changeReason:''}],
 patients:[{id:'p1',file:'OR-1001',name:'سارة محمد',phone:'+90 555 120 2244',nationalId:'',age:'32',birth:'1994-05-12',blood:'A+',allergy:'بنسلين',chronic:'لا يوجد',meds:'لا يوجد',doctorNotes:'متابعة الإطباق في الجلسة القادمة.',contact:'محمد — +90 555 331 1122',balance:'5300'},{id:'p2',file:'OR-1002',name:'عمر خالد',phone:'+90 555 771 3900',nationalId:'',age:'38',birth:'1988-11-02',blood:'O+',allergy:'لا يوجد',chronic:'سكري',meds:'Metformin',doctorNotes:'قياس السكر قبل الإجراء.',contact:'نور — +90 555 992 7711',balance:'0'}],
 sessions:[{id:'s1',patientId:'p1',patient:'سارة محمد',number:'3',doctor:'د. أحمد سامي',date:'2026-09-01',type:'مرحلة علاج',procedure:'ترميم السن 16',visible:'تم تنظيف التسوس ووضع حشوة دائمة.',internal:'متابعة الإطباق في الزيارة القادمة',material:'كومبوزيت',qty:'1',status:'مكتملة',startedAt:'2026-09-01 10:32'}],
 plans:[{id:'pl1',patientId:'p1',patient:'سارة محمد',title:'علاج وترميم',cost:'8500',paid:'3200',progress:'42',nextStep:'علاج السن 17',expiry:'2026-10-01',status:'نشطة'}],
 prescriptions:[{id:'rx1',patientId:'p1',patient:'سارة محمد',doctor:'د. أحمد سامي',date:'2026-09-01',medicine:'Ibuprofen 400mg',dose:'بعد الأكل عند اللزوم',instructions:'لا تتجاوز 3 أقراص يوميًا'}],
 imaging:[{id:'im1',patientId:'p1',patient:'سارة محمد',type:'أشعة بانوراما',date:'2026-08-28',note:'للتشخيص الأولي',fileName:'panorama-example.jpg',fileData:''}],
 finance:[{id:'f1',patientId:'p1',person:'سارة محمد',type:'دفعة',amount:'3200',date:'2026-09-01',method:'بطاقة',status:'معتمدة'},{id:'f2',patientId:'',person:'مستلزمات',type:'مصروف',amount:'850',date:'2026-09-02',method:'نقدي',status:'معتمدة'}],
 inventory:[{id:'i1',item:'كومبوزيت',category:'حشوات',qty:'8',min:'5',cost:'160',supplier:'Dental Pro'},{id:'i2',item:'قفازات',category:'وقاية',qty:'3',min:'10',cost:'90',supplier:'Med Supply'}],
 labs:[{id:'l1',patientId:'p1',patient:'سارة محمد',lab:'Istanbul Lab',work:'تاج زركون',sent:'2026-09-02',due:'2026-09-10',cost:'1400',status:'قيد التنفيذ'}],
 staff:[{id:'u0',name:'مدير ORAVENA',email:'admin@oravena.demo',password:'1234',systemRole:'admin',role:'مدير رئيسي',phone:'',shift:'',status:'نشط',permissions:allSections.join(',')},{id:'u1',name:'أحمد سامي',email:'doctor@oravena.demo',password:'1234',systemRole:'doctor',role:'دكتور',phone:'+90 555 444 1010',shift:'09:00–17:00',status:'نشط',permissions:permissionTemplates['الدكتور'].join(',')},{id:'u2',name:'هدى علي',email:'employee@oravena.demo',password:'1234',systemRole:'employee',role:'استقبال',phone:'+90 555 444 3030',shift:'08:30–16:30',status:'نشط',permissions:permissionTemplates['الاستقبال'].join(',')}],
 messages:[{id:'m1',patientId:'p1',patient:'سارة محمد',topic:'موعد',subject:'تغيير موعد المتابعة',message:'هل يمكن نقل الموعد إلى الساعة 12؟',status:'جديدة'}],notifications:[{id:'n1',title:'طلب موعد جديد',text:'موعد عمر خالد بانتظار التحديد.',patientId:'p2',read:false}],audit:[{id:'log1',date:now(),user:'النظام',action:'تشغيل النسخة',details:'تم تحميل بيانات الاختبار'}],
 teeth:{p1:{...blankTeeth(),5:{status:'caries',stage:'تشخيص',needs:'تنظيف وحشو',note:'تسوس سطحي مسجل 2026-08-28'},12:{status:'treated',stage:'متابعة',needs:'فحص الإطباق',note:'حشوة دائمة 2026-09-01'}},p2:blankTeeth()},settings:{clinic:'ORAVENA Dental',currency:'TRY',appointmentDuration:'30',lateMinutes:'15',planDays:'30',adultAge:'18',inventory:true,labs:true,notifications:true}
}}
function loadDb(){let raw=null;try{raw=JSON.parse(localStorage.getItem(KEY)||'null')}catch{}const seed=demoSeed();if(!raw)return seed;const emptyWhenBooking=['sessions','plans','prescriptions','imaging','finance','inventory','labs','messages','audit','teeth'];for(const key of Object.keys(seed))if(raw[key]===undefined)raw[key]=raw.schemaVersion===3&&emptyWhenBooking.includes(key)?(key==='teeth'?{}:[]):seed[key];for(const p of raw.patients||[]){p.id=p.id||uid('p');raw.teeth[p.id]=raw.teeth[p.id]||blankTeeth()}return raw}
let db=loadDb(),role=new URLSearchParams(location.search).get('role')||localStorage.getItem('oravenaRole')||'admin',sessionEmail=localStorage.getItem('oravenaSessionEmail')||'',section='dashboard',editing=null,filter='',selectedPatientId=localStorage.getItem('oravenaPatientId')||db.patients[0]?.id||'';
const save=()=>localStorage.setItem(KEY,JSON.stringify(db)),currentUser=()=>db.staff.find(u=>u.email.toLowerCase()===sessionEmail.toLowerCase()),currentUserName=()=>currentUser()?.name||({admin:'المدير الرئيسي',doctor:'الدكتور',employee:'الموظف',patient:'المريض'})[role];
const log=(action,details='')=>{db.audit.unshift({id:uid('log'),date:now(),user:currentUserName(),action,details});save()};
function allowedSections(){if(role==='admin')return allSections;if(role==='patient')return ['dashboard','appointments','sessions','odontogram','plans','prescriptions','imaging','finance','messages'];const account=currentUser();if(account?.permissions)return account.permissions.split(',').filter(Boolean);return role==='doctor'?permissionTemplates['الدكتور']:permissionTemplates['الاستقبال']}
const defs={
 appointments:{cols:{patient:'المريض',service:'الخدمة',date:'التاريخ',time:'الوقت',doctor:'الدكتور',status:'الحالة'},fields:[['patientId','المريض','patient'],['service','الخدمة','text'],['date','التاريخ','date',null,false],['time','الوقت','time',null,false],['doctor','الدكتور','text',null,false],['status','الحالة','select','طلب جديد|مؤكد|معدل|ملغي|مكتمل'],['changeReason','سبب التعديل (اختياري)','textarea',null,false]]},
 patients:{cols:{file:'رقم الملف',name:'الاسم',phone:'الهاتف',age:'السن',allergy:'الحساسية',balance:'المتبقي'},fields:[['file','رقم الملف','text'],['name','الاسم الكامل','text'],['phone','الهاتف','tel'],['nationalId','رقم الهوية (اختياري)','text',false],['age','السن','number'],['birth','تاريخ الميلاد','date',false],['blood','فصيلة الدم','text',false],['allergy','الحساسية','text',false],['chronic','الأمراض المزمنة','text',false],['meds','الأدوية الحالية','textarea',false],['doctorNotes','ملاحظات الطبيب','textarea',false],['contact','اتصال الطوارئ','text',false],['balance','المبلغ المتبقي','number',false]]},
 sessions:{cols:{patient:'المريض',number:'رقم الجلسة',type:'النوع',doctor:'الدكتور',date:'التاريخ',status:'الحالة'},fields:[['patientId','المريض','patient'],['number','رقم الجلسة','number',false],['doctor','الدكتور','text'],['date','التاريخ','date'],['type','نوع الجلسة','select','فحص|متابعة|مرحلة علاج|طوارئ'],['procedure','ما تم في الجلسة','textarea'],['visible','ملخص يظهر للمريض','textarea',false],['internal','ملاحظات الطبيب الداخلية','textarea',false],['material','المادة المستخدمة','inventory',false],['qty','الكمية','number',false],['status','الحالة','select','مجدولة|بدأت|مكتملة|ملغاة']]},
 plans:{cols:{patient:'المريض',title:'الخطة',progress:'التقدم %',nextStep:'الخطوة القادمة',cost:'التكلفة',paid:'المدفوع',status:'الحالة'},fields:[['patientId','المريض','patient'],['title','اسم الخطة','text'],['cost','التكلفة','number'],['paid','المدفوع','number'],['progress','التقدم %','number'],['nextStep','الخطوة القادمة','text',false],['expiry','تاريخ المراجعة','date',false],['status','الحالة','select','مسودة|نشطة|مكتملة|متوقفة']]},
 prescriptions:{cols:{patient:'المريض',doctor:'الدكتور',date:'التاريخ',medicine:'الدواء',dose:'الجرعة'},fields:[['patientId','المريض','patient'],['doctor','الدكتور','text'],['date','التاريخ','date'],['medicine','الدواء','text'],['dose','الجرعة','text'],['instructions','التعليمات','textarea',false]]},
 imaging:{cols:{patient:'المريض',type:'النوع',date:'التاريخ',fileName:'الملف',note:'الملاحظة'},fields:[['patientId','المريض','patient'],['type','نوع الصورة/الأشعة','select','صورة أسنان|أشعة بانوراما|CBCT|أشعة موضعية|قبل وبعد'],['date','التاريخ','date'],['note','الملاحظة','textarea',false],['fileData','رفع صورة أو أشعة','file',false]]},
 finance:{cols:{person:'البيان',type:'النوع',amount:'المبلغ',date:'التاريخ',method:'الطريقة',status:'الحالة'},fields:[['patientId','المريض (اختياري)','patientOptional',false],['person','البيان/اسم المريض','text'],['type','نوع الحركة','select','دفعة|مصروف|استرداد'],['amount','المبلغ','number'],['date','التاريخ','date'],['method','طريقة الدفع','select','نقدي|بطاقة|تحويل'],['status','الحالة','select','مسودة|معتمدة']]},
 inventory:{cols:{item:'الصنف',category:'التصنيف',qty:'الكمية',min:'الحد الأدنى',cost:'التكلفة',supplier:'المورد'},fields:[['item','الصنف','text'],['category','التصنيف','text'],['qty','الكمية','number'],['min','الحد الأدنى','number'],['cost','تكلفة الوحدة','number'],['supplier','المورد','text',false]]},
 labs:{cols:{patient:'المريض',lab:'المعمل',work:'العمل',sent:'الإرسال',due:'التسليم',cost:'التكلفة',status:'الحالة'},fields:[['patientId','المريض','patient'],['lab','المعمل','text'],['work','العمل المطلوب','text'],['sent','تاريخ الإرسال','date'],['due','موعد التسليم','date'],['cost','التكلفة','number'],['status','الحالة','select','قيد التنفيذ|وصل|مرفوض|تم التسليم']]},
 staff:{cols:{name:'الاسم',email:'البريد',role:'المسمى',status:'الحساب',permissions:'الأقسام المسموحة'},fields:[['name','الاسم','text'],['email','البريد الوظيفي','email'],['password','كلمة المرور التجريبية','text'],['systemRole','نوع الحساب','select','doctor|employee'],['role','المسمى الوظيفي','text'],['phone','الهاتف','tel',false],['shift','الوردية','text',false],['status','الحالة','select','نشط|موقوف'],['permissions','قوالب وأقسام الصلاحيات','permissions']]},
 messages:{cols:{patient:'المريض',topic:'الموضوع',subject:'العنوان',message:'الرسالة',status:'الحالة'},fields:[['patientId','المريض','patient'],['topic','نوع الموضوع','select','موعد|علاج|حساب|ملف'],['subject','العنوان','text'],['message','الرسالة','textarea'],['status','الحالة','select','جديدة|قيد المتابعة|تم الرد']]}
};
const patientById=id=>db.patients.find(p=>p.id===id),currentPatient=()=>patientById(selectedPatientId)||db.patients[0],patientRows=k=>(db[k]||[]).filter(r=>r.patientId===currentPatient()?.id||(!r.patientId&&r.patient===currentPatient()?.name));
function normalizeRecord(k,data,old={}){if(data.patientId){const p=patientById(data.patientId);data.patient=p?.name||old.patient||'';if(k==='finance'&&!data.person)data.person=data.patient}if(k==='sessions'&&!data.number)data.number=String(db.sessions.filter(s=>s.patientId===data.patientId).length+1);return data}
function nav(){const menus=allowedSections();if(section!=='patientRecord'&&!menus.includes(section))section='dashboard';$('#sideNav').innerHTML=menus.map(k=>`<button class="nav-btn ${k===section?'active':''}" data-section="${k}"><i>${sectionIcons[k]}</i>${sectionLabels[k]}</button>`).join('');document.querySelectorAll('[data-section]').forEach(b=>b.onclick=()=>{section=b.dataset.section;filter='';$('#globalSearch').value='';render()})}
const stat=(label,value,note='')=>`<div class="stat"><small>${label}</small><strong>${esc(value)}</strong><span>${esc(note)}</span></div>`;
function dashboard(){if(role==='patient')return patientHome();const income=db.finance.filter(x=>x.type==='دفعة').reduce((a,x)=>a+(+x.amount||0),0),expenses=db.finance.filter(x=>x.type!=='دفعة').reduce((a,x)=>a+(+x.amount||0),0);return `<div class="stats">${stat('طلبات المواعيد',db.appointments.filter(x=>x.status==='طلب جديد').length,'تحتاج تحديدًا أو تأكيدًا')}${stat('المرضى والعملاء',db.patients.length,'ملفات محفوظة')}${stat('صافي التحصيل',(income-expenses).toLocaleString()+' ₺','بعد المصروفات والاسترداد')}${stat('تنبيهات المخزون',db.inventory.filter(x=>+x.qty<=+x.min).length,'تحتاج مراجعة')}</div><div class="grid-2"><div class="panel"><div class="panel-head"><h2>مواعيد قريبة</h2><button class="mini" data-go="appointments">عرض الكل</button></div>${table('appointments',db.appointments.slice(0,5),false)}</div><div class="panel"><h2>إجراءات سريعة</h2><div class="quick-actions"><button data-new="appointments">＋ موعد</button><button data-new="patients">＋ مريض</button><button data-new="sessions">＋ جلسة</button><button data-new="imaging">＋ أشعة</button></div><h3>آخر العمليات</h3><ul class="activity">${db.audit.slice(0,5).map(x=>`<li><b>${esc(x.action)}</b><small>${esc(x.date)} · ${esc(x.user)}</small></li>`).join('')}</ul></div></div>`}
function patientHome(){const p=currentPatient();if(!p)return '<div class="empty">لا يوجد ملف مريض.</div>';const ap=patientRows('appointments').filter(x=>!['ملغي','مكتمل'].includes(x.status))[0],plan=patientRows('plans')[0],last=patientRows('sessions')[0];return `<div class="notice patient-switch">ملف المريض <select id="familySwitch">${db.patients.map(x=>`<option value="${x.id}" ${x.id===p.id?'selected':''}>${esc(x.name)} — ${esc(x.file)}</option>`).join('')}</select></div><div class="stats">${stat('الموعد القادم',ap?.date||'بانتظار التحديد',ap?.time||ap?.status||'')}${stat('تقدم العلاج',(plan?.progress||0)+'%',plan?.title||'لا توجد خطة')}${stat('المبلغ المتبقي',(p.balance||0)+' ₺',+p.balance?'غير مدفوع بالكامل':'مسدد')}${stat('الجلسات',patientRows('sessions').length,last?.status||'')}</div><div class="grid-2"><div class="panel"><div class="panel-head"><h2>العلاج الحالي</h2><span class="badge ok">${esc(plan?.status||'لا توجد خطة')}</span></div><h3>${esc(plan?.title||'لم تُضف خطة بعد')}</h3><p class="muted">الخطوة القادمة: ${esc(plan?.nextStep||'يحددها الطبيب')}</p><div class="progress-bar"><i style="width:${Math.min(100,+plan?.progress||0)}%"></i></div><div class="quick-actions"><button data-go="appointments">المواعيد</button><button data-go="prescriptions">الأدوية والوصفات</button><button data-go="imaging">الصور والأشعة</button><button data-go="odontogram">خريطة الأسنان</button></div></div><div class="panel"><h2>ملاحظات الطبيب</h2><p>${esc(p.doctorNotes||'لا توجد ملاحظات مشاركة حاليًا.')}</p><h3>آخر جلسة</h3><p>${esc(last?.visible||'لا توجد جلسات مسجلة.')}</p><small class="muted">الملاحظات الطبية الداخلية لا تظهر في حساب المريض.</small></div></div>`}
function visibleRows(k){let rows=db[k]||[];if(role==='patient')rows=patientRows(k).map(x=>k==='sessions'?Object.fromEntries(Object.entries(x).filter(([key])=>key!=='internal')):x);if(filter){const f=filter.toLowerCase();rows=rows.filter(x=>Object.values(x).some(v=>String(v).toLowerCase().includes(f)))}return rows}
const statusBadge=v=>String(v||'').includes('ملغ')?'danger':String(v||'').match(/طلب|بدأ|تنفيذ/) ?'warn':'ok';
function table(k,rows=visibleRows(k),actions=true){const d=defs[k];if(!rows.length)return '<div class="empty"><b>⌕</b>لا توجد سجلات</div>';return `<div class="table-wrap"><table class="data-table"><thead><tr>${Object.values(d.cols).map(v=>`<th>${v}</th>`).join('')}${actions?'<th>الإجراءات</th>':''}</tr></thead><tbody>${rows.map(r=>`<tr>${Object.keys(d.cols).map(c=>`<td>${c==='status'?`<span class="badge ${statusBadge(r[c])}">${esc(r[c])}</span>`:c==='permissions'?esc(String(r[c]||'').split(',').map(x=>sectionLabels[x]||x).join('، ')):c==='fileName'&&r.fileData?`<button class="mini" data-preview="${r.id}">${esc(r.fileName||'فتح الملف')}</button>`:esc(r[c])}</td>`).join('')}${actions?`<td><div class="row-actions">${k==='patients'?`<button class="mini" data-patient="${r.id}">فتح الملف</button>`:''}${k==='sessions'&&!['بدأت','مكتملة'].includes(r.status)?`<button class="mini start" data-start="${r.id}">بدء الجلسة</button>`:''}${role!=='patient'?`<button class="mini edit" data-edit="${k}:${r.id}">تعديل</button><button class="mini delete" data-delete="${k}:${r.id}">حذف</button>`:''}</div></td>`:''}</tr>`).join('')}</tbody></table></div>`}
function listPage(k){let extra='';if(k==='finance'){const paid=db.finance.filter(x=>x.type==='دفعة').reduce((a,x)=>a+(+x.amount||0),0),out=db.finance.filter(x=>x.type!=='دفعة').reduce((a,x)=>a+(+x.amount||0),0);extra=`<div class="stats">${stat('الدفعات',paid+' ₺')}${stat('المصروفات والاسترداد',out+' ₺')}${stat('الصافي',(paid-out)+' ₺')}${stat('العملة',db.settings.currency)}</div>`}return extra+`<div class="panel"><div class="panel-head"><h2>${sectionLabels[k]}</h2><span class="muted">${visibleRows(k).length} سجل</span></div>${table(k)}</div>`}
function patientRecord(){const p=currentPatient();if(!p)return '<div class="empty">لم يتم العثور على المريض.</div>';const groups=[['appointments','المواعيد'],['sessions','الجلسات'],['plans','خطة العلاج'],['prescriptions','الوصفات'],['imaging','الصور والأشعة']];return `<div class="record-hero"><div><small>${esc(p.file)}</small><h2>${esc(p.name)}</h2><p>${esc(p.phone)} · ${esc(p.age)} سنة</p></div><div class="record-actions"><button class="secondary" data-edit="patients:${p.id}">تعديل البيانات</button><button class="primary" data-record-go="odontogram">خريطة الأسنان 3D</button></div></div><div class="profile-grid">${[['فصيلة الدم',p.blood],['الحساسية',p.allergy],['أمراض مزمنة',p.chronic],['الأدوية الحالية',p.meds],['المتبقي',`${p.balance||0} ₺`],['ملاحظات الطبيب',p.doctorNotes]].map(x=>`<div><small>${x[0]}</small><b>${esc(x[1]||'غير مسجل')}</b></div>`).join('')}</div>${groups.map(([k,t])=>`<div class="panel record-section"><div class="panel-head"><h2>${t}</h2><button class="mini" data-new-for="${k}:${p.id}">إضافة</button></div>${table(k,patientRows(k))}</div>`).join('')}`}
function odontogram(){const p=currentPatient();if(!p)return '<div class="empty">أضف مريضًا أولًا.</div>';const teeth=db.teeth[p.id]||(db.teeth[p.id]=blankTeeth());return `<div class="patient-context"><label>خريطة المريض <select id="toothPatient">${db.patients.map(x=>`<option value="${x.id}" ${x.id===p.id?'selected':''}>${esc(x.name)} — ${esc(x.file)}</option>`).join('')}</select></label><span>مرّر على السن للتفاصيل، واضغط للتعديل</span></div><div class="odontogram odontogram-3d"><div class="gum"><span>الفك العلوي</span><div class="jaw">${Array.from({length:16},(_,i)=>tooth(i+1,teeth[i+1])).join('')}</div></div><div class="gum lower-gum"><div class="jaw lower">${Array.from({length:16},(_,i)=>tooth(i+17,teeth[i+17])).join('')}</div><span>الفك السفلي</span></div><div class="legend"><span><i class="healthy"></i>سليم</span><span><i class="caries"></i>تسوس</span><span><i class="treated"></i>معالج</span><span><i class="missing"></i>مفقود</span><span><i class="planned"></i>مخطط</span></div></div>`}
function tooth(n,t){const history=(t.history||[]).slice(-2).map(h=>`${h.date}: ${h.status} — ${h.stage||'بدون مرحلة'}`).join('\n');const tip=`السن ${n} — ${statusName(t.status)}\nالمرحلة: ${t.stage||'غير مسجلة'}\nيحتاج: ${t.needs||'لا يوجد'}\nالتفاصيل: ${t.note||'لا توجد تفاصيل'}${history?'\nسجل سابق:\n'+history:''}`;return `<button class="tooth ${t.status}" data-tooth="${n}" title="${esc(tip)}"><span class="tooth-crown"></span><b>${n}</b><span class="tooth-tip">${esc(tip).replaceAll('\n','<br>')}</span></button>`}
const statusName=s=>({healthy:'سليم',caries:'تسوس',treated:'معالج',missing:'مفقود',implant:'زراعة',planned:'إجراء مخطط'})[s]||s;
function reports(){return `<div class="stats">${stat('المرضى',db.patients.length)}${stat('المواعيد',db.appointments.length)}${stat('الجلسات المكتملة',db.sessions.filter(x=>x.status==='مكتملة').length)}${stat('خطط نشطة',db.plans.filter(x=>x.status==='نشطة').length)}</div><div class="panel"><h2>تصدير التقرير والبيانات</h2><p class="muted">يمكن تنزيل نسخة JSON كاملة واستعادتها لاحقًا.</p><button class="primary" id="reportExport">تصدير الآن</button></div>`}
function audit(){return `<div class="panel"><div class="panel-head"><h2>سجل العمليات</h2><span class="badge">${db.audit.length} عملية</span></div><div class="table-wrap"><table class="data-table"><thead><tr><th>التاريخ</th><th>المستخدم</th><th>العملية</th><th>التفاصيل</th></tr></thead><tbody>${db.audit.map(x=>`<tr><td>${esc(x.date)}</td><td>${esc(x.user)}</td><td>${esc(x.action)}</td><td>${esc(x.details)}</td></tr>`).join('')}</tbody></table></div></div>`}
function settings(){return `<div class="grid-2"><div class="panel"><h2>الإعدادات العامة</h2><div class="form-grid" id="settingsForm"><label>اسم العيادة<input data-setting="clinic" value="${esc(db.settings.clinic)}"></label><label>العملة<select data-setting="currency"><option ${db.settings.currency==='TRY'?'selected':''}>TRY</option><option>USD</option><option>EUR</option></select></label><label>مدة الموعد بالدقائق<input type="number" data-setting="appointmentDuration" value="${esc(db.settings.appointmentDuration)}"></label><label>سن استقلال حساب الطفل<input type="number" data-setting="adultAge" value="${esc(db.settings.adultAge)}"></label></div><button class="primary" id="saveSettings">حفظ الإعدادات</button></div><div class="panel"><h2>حسابات الدخول التجريبية</h2><p><b>الإدارة:</b> admin@oravena.demo</p><p><b>الدكتور:</b> doctor@oravena.demo</p><p><b>الموظف:</b> employee@oravena.demo</p><p class="muted">كلمة المرور التجريبية: 1234</p></div></div><div class="panel danger-zone"><h2>بيانات النسخة المحلية</h2><p class="muted">«إعادة التجريبي» تعيد أمثلة النظام. «تصفير كامل» يمسح المرضى والمواعيد وكل سجلات التشغيل ويُبقي الإعدادات وحساب المدير فقط.</p><div class="toolbar"><button class="secondary" id="importButton">استيراد نسخة</button><button class="secondary" id="settingsExport">تصدير نسخة</button><button class="danger-btn" id="resetDemo">إعادة البيانات التجريبية</button><button class="danger-btn strong" id="clearAll">تصفير كل البيانات</button></div></div>`}
function render(){nav();$('#roleSelect').value=role;$('#signedUser').textContent=sessionEmail||'وضع تجربة مباشر';$('#pageTitle').textContent=section==='patientRecord'?'ملف المريض':sectionLabels[section];$('#pageKicker').textContent=currentUserName();const canAdd=defs[section]&&role!=='patient';$('#primaryAction').hidden=!canAdd;$('#primaryAction').textContent=section==='messages'?'رسالة جديدة':'إضافة جديد';$('#globalSearch').disabled=!defs[section];$('#content').innerHTML=section==='dashboard'?dashboard():section==='patientRecord'?patientRecord():section==='odontogram'?odontogram():section==='reports'?reports():section==='audit'?audit():section==='settings'?settings():listPage(section);wire();updateNotifications()}
function wire(){document.querySelectorAll('[data-go]').forEach(b=>b.onclick=()=>{section=b.dataset.go;render()});document.querySelectorAll('[data-new]').forEach(b=>b.onclick=()=>openEditor(b.dataset.new));document.querySelectorAll('[data-edit]').forEach(b=>b.onclick=()=>{const[k,id]=b.dataset.edit.split(':');openEditor(k,id)});document.querySelectorAll('[data-delete]').forEach(b=>b.onclick=()=>remove(...b.dataset.delete.split(':')));document.querySelectorAll('[data-patient]').forEach(b=>b.onclick=()=>{selectedPatientId=b.dataset.patient;localStorage.setItem('oravenaPatientId',selectedPatientId);section='patientRecord';render()});document.querySelectorAll('[data-record-go]').forEach(b=>b.onclick=()=>{section=b.dataset.recordGo;render()});document.querySelectorAll('[data-new-for]').forEach(b=>b.onclick=()=>{const[k,p]=b.dataset.newFor.split(':');openEditor(k,null,p)});document.querySelectorAll('[data-start]').forEach(b=>b.onclick=()=>startSession(b.dataset.start));document.querySelectorAll('[data-tooth]').forEach(b=>b.onclick=()=>openTooth(b.dataset.tooth));document.querySelectorAll('[data-preview]').forEach(b=>b.onclick=()=>previewImage(b.dataset.preview));$('#familySwitch')?.addEventListener('change',e=>{selectedPatientId=e.target.value;localStorage.setItem('oravenaPatientId',selectedPatientId);render()});$('#toothPatient')?.addEventListener('change',e=>{selectedPatientId=e.target.value;localStorage.setItem('oravenaPatientId',selectedPatientId);render()});$('#saveSettings')?.addEventListener('click',()=>{document.querySelectorAll('[data-setting]').forEach(i=>db.settings[i.dataset.setting]=i.value);log('تحديث الإعدادات');toast('تم حفظ الإعدادات')});$('#resetDemo')?.addEventListener('click',()=>{if(confirm('إعادة كل بيانات الاختبار الأصلية؟')){db=demoSeed();save();selectedPatientId=db.patients[0].id;render();toast('تمت إعادة البيانات التجريبية')}});$('#clearAll')?.addEventListener('click',clearAllData);$('#importButton')?.addEventListener('click',()=>$('#importInput').click());$('#settingsExport')?.addEventListener('click',exportData);$('#reportExport')?.addEventListener('click',exportData)}
function inputFor([k,l,t,opts,required],v=''){const req=required===false?'':'required';if(t==='textarea')return `<label class="wide">${l}<textarea name="${k}" rows="3" ${req}>${esc(v)}</textarea></label>`;if(t==='select')return `<label>${l}<select name="${k}" ${req}>${String(opts).split('|').map(o=>`<option ${v===o?'selected':''}>${o}</option>`).join('')}</select></label>`;if(t==='patient'||t==='patientOptional')return `<label>${l}<select name="${k}" ${req}>${t==='patientOptional'?'<option value="">بدون مريض</option>':''}${db.patients.map(p=>`<option value="${p.id}" ${v===p.id?'selected':''}>${esc(p.name)} — ${esc(p.file)}</option>`).join('')}</select></label>`;if(t==='inventory')return `<label>${l}<select name="${k}"><option value="">بدون مادة</option>${db.inventory.map(x=>`<option ${v===x.item?'selected':''}>${esc(x.item)}</option>`).join('')}</select></label>`;if(t==='file')return `<label class="wide">${l}<input name="${k}" type="file" accept="image/*,.pdf"><small>${v?'يوجد ملف محفوظ — ارفع ملفًا آخر للاستبدال':'يُحفظ داخل هذا المتصفح فقط'}</small></label>`;if(t==='permissions')return `<fieldset class="wide permission-grid"><legend>${l}</legend>${Object.entries(permissionTemplates).map(([name,parts])=>`<label class="template"><input type="checkbox" data-template="${esc(parts.join(','))}"> ${name}</label>`).join('')}${allSections.filter(x=>!['settings','audit'].includes(x)).map(x=>`<label><input type="checkbox" name="permissions" value="${x}" ${String(v||'').split(',').includes(x)?'checked':''}> ${sectionLabels[x]}</label>`).join('')}</fieldset>`;return `<label>${l}<input name="${k}" type="${t}" value="${esc(v)}" ${t==='number'?'min="0"':''} ${req}></label>`}
function openEditor(k,id=null,patientId=''){editing={k,id};const d=defs[k],rec=id?db[k].find(x=>x.id===id):patientId?{patientId}:{date:today()};$('#editorTitle').textContent=(id?'تعديل ':'إضافة ')+sectionLabels[k];$('#editorFields').innerHTML=d.fields.map(f=>inputFor(f,rec?.[f[0]])).join('');document.querySelectorAll('[data-template]').forEach(box=>box.onchange=()=>{if(box.checked)box.dataset.template.split(',').forEach(v=>{const c=document.querySelector(`input[name="permissions"][value="${v}"]`);if(c)c.checked=true})});$('#editorDialog').showModal()}
async function formDataWithFiles(form){const data={};for(const el of form.elements){if(!el.name)continue;if(el.name==='permissions'){data.permissions=Array.from(form.querySelectorAll('[name="permissions"]:checked')).map(x=>x.value).join(',');continue}if(el.type==='file'){const file=el.files[0];if(file){data.fileName=file.name;data.fileData=await new Promise(ok=>{const r=new FileReader();r.onload=()=>ok(r.result);r.readAsDataURL(file)})}continue}data[el.name]=el.value}return data}
$('#editorForm').onsubmit=async e=>{e.preventDefault();let data=await formDataWithFiles(e.currentTarget),{k,id}=editing,old=id?db[k].find(x=>x.id===id):{};data=normalizeRecord(k,data,old);if(id){Object.assign(old,data);log('تعديل '+sectionLabels[k],data.patient||data.name||id);if(k==='appointments')db.notifications.unshift({id:uid('n'),title:'تم تعديل الموعد',text:`${data.patient}: ${data.date||'موعد غير محدد'} ${data.time||''}${data.changeReason?' — السبب: '+data.changeReason:''}`,patientId:data.patientId,read:false})}else{db[k].unshift({id:uid(k.slice(0,2)),...data});log('إضافة '+sectionLabels[k],data.patient||data.name||data.item||'سجل جديد')}if(k==='sessions'&&data.material&&+data.qty){const item=db.inventory.find(x=>x.item===data.material);if(item)item.qty=String(Math.max(0,+item.qty-(+data.qty)))}save();$('#editorDialog').close();render();toast('تم الحفظ بنجاح')};
function remove(k,id){if(!confirm('هل تريد حذف هذا السجل؟'))return;const r=db[k].find(x=>x.id===id);db[k]=db[k].filter(x=>x.id!==id);if(k==='patients'){for(const rel of ['appointments','sessions','plans','prescriptions','imaging','finance','labs','messages'])db[rel]=db[rel].filter(x=>x.patientId!==id);delete db.teeth[id]}log('حذف '+sectionLabels[k],r?.name||r?.patient||r?.item||id);render();toast('تم الحذف')}
function startSession(id){const s=db.sessions.find(x=>x.id===id);if(!s)return;s.status='بدأت';s.startedAt=now();s.number=s.number||String(db.sessions.filter(x=>x.patientId===s.patientId).length);log('بدء جلسة',`${s.patient} — الجلسة ${s.number}`);render();toast(`بدأت الجلسة رقم ${s.number}`)}
function openTooth(n){const p=currentPatient(),t=(db.teeth[p.id]||blankTeeth())[n];$('#toothId').value=n;$('#toothNumber').textContent=n;$('#toothStatus').value=t.status;$('#toothStage').value=t.stage||'';$('#toothNeeds').value=t.needs||'';$('#toothNote').value=t.note||'';$('#toothDialog').showModal()}
$('#toothForm').onsubmit=e=>{e.preventDefault();const p=currentPatient(),n=$('#toothId').value;db.teeth[p.id]=db.teeth[p.id]||blankTeeth();const old=db.teeth[p.id][n]||{},history=old.history||[];if(old.status||old.stage||old.note)history.push({date:now(),status:statusName(old.status),stage:old.stage||'',note:old.note||''});db.teeth[p.id][n]={status:$('#toothStatus').value,stage:$('#toothStage').value,needs:$('#toothNeeds').value,note:$('#toothNote').value,history};log('تحديث خريطة الأسنان',`${p.name} — السن ${n}`);$('#toothDialog').close();render();toast('تم حفظ تفاصيل السن ومراحل علاجه')};
function previewImage(id){const r=db.imaging.find(x=>x.id===id);if(!r?.fileData)return toast('لا يوجد ملف معاينة');const w=open('','_blank');w.document.write(r.fileData.startsWith('data:application/pdf')?`<iframe src="${r.fileData}" style="width:100%;height:100vh;border:0"></iframe>`:`<img src="${r.fileData}" style="max-width:100%;display:block;margin:auto">`)}
function download(name,text){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([text],{type:'application/json'}));a.download=name;a.click();URL.revokeObjectURL(a.href)}function exportData(){log('تصدير نسخة احتياطية','JSON');download('oravena-local-backup.json',JSON.stringify(db,null,2));toast('تم تصدير النسخة')}
function clearAllData(){if(!confirm('سيتم حذف كل بيانات التشغيل المحلية. هل أنت متأكد؟'))return;const admin=db.staff.find(x=>x.systemRole==='admin')||demoSeed().staff[0],settings=db.settings;db={...demoSeed(),appointments:[],patients:[],sessions:[],plans:[],prescriptions:[],imaging:[],finance:[],inventory:[],labs:[],messages:[],notifications:[],teeth:{},staff:[admin],audit:[],settings};log('تصفير كامل','تم مسح بيانات التشغيل');selectedPatientId='';render();toast('تم تصفير كل البيانات')}
$('#importInput').onchange=e=>{const f=e.target.files[0];if(!f)return;const r=new FileReader();r.onload=()=>{try{const x=JSON.parse(r.result);if(!x.patients||!x.settings)throw Error();db=x;log('استيراد نسخة',f.name);render();toast('تم الاستيراد')}catch{toast('الملف غير صالح')}};r.readAsText(f);e.target.value=''};
function updateNotifications(){let rows=db.notifications;if(role==='patient')rows=rows.filter(x=>!x.patientId||x.patientId===currentPatient()?.id);const n=rows.filter(x=>!x.read).length;$('#notificationCount').textContent=n;$('#notificationCount').hidden=!n;$('#notificationsList').innerHTML=rows.map(x=>`<div class="notifications-item ${x.read?'':'unread'}"><strong>${esc(x.title)}</strong><p>${esc(x.text)}</p></div>`).join('')||'<p class="muted">لا توجد إشعارات.</p>'}
$('#notificationsButton').onclick=()=>$('#notificationsDialog').showModal();$('#readAllButton').onclick=()=>{db.notifications.forEach(x=>x.read=true);save();updateNotifications();toast('تمت قراءة التنبيهات')};
$('#emergencyButton').onclick=()=>{const p=currentPatient()||db.patients[0];if(!p)return toast('لا يوجد مريض');$('#emergencyContent').innerHTML=`<div class="emergency-data"><div><small>المريض</small>${esc(p.name)}</div><div><small>رقم الملف</small>${esc(p.file)}</div><div><small>فصيلة الدم</small>${esc(p.blood)}</div><div><small>الحساسية</small>${esc(p.allergy)}</div><div><small>أمراض مزمنة</small>${esc(p.chronic)}</div><div><small>الأدوية الحالية</small>${esc(p.meds)}</div><div><small>اتصال الطوارئ</small>${esc(p.contact)}</div></div>`;$('#emergencyDialog').showModal()};$('#recordEmergencyButton').onclick=()=>{const reason=prompt('اكتب سبب الوصول الطبي الطارئ');if(reason){log('وصول طبي طارئ',reason);$('#emergencyDialog').close();toast('تم تسجيل السبب')}};
$('#primaryAction').onclick=()=>openEditor(section);$('#exportButton').onclick=exportData;$('#roleSelect').onchange=e=>{role=e.target.value;localStorage.setItem('oravenaRole',role);section='dashboard';render();toast('تم التبديل إلى '+currentUserName())};$('#globalSearch').oninput=e=>{filter=e.target.value;render()};$('#sideToggle').onclick=()=>$('#side').classList.toggle('open');document.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>document.getElementById(b.dataset.close).close());
function connection(){const off=!navigator.onLine;$('#connection').classList.toggle('offline',off);$('#connection span').textContent=off?'غير متصل — الحفظ محلي':'متصل — الحفظ محلي'}addEventListener('online',connection);addEventListener('offline',connection);connection();let toastTimer;function toast(s){$('#toast').textContent=s;$('#toast').classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').classList.remove('show'),2600)}document.body.dataset.role=role;$('#roleSelect').addEventListener('change',()=>requestAnimationFrame(()=>document.body.dataset.role=role));save();render();
