const KEY='oravena_demo_system_v2';
const $=s=>document.querySelector(s), esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const now=()=>new Date().toLocaleString('ar-EG'), uid=()=>Date.now().toString(36)+Math.random().toString(36).slice(2,6);
const seed=()=>({
 appointments:[{id:'a1',patient:'سارة محمد',doctor:'د. أحمد سامي',service:'متابعة علاج',date:'2026-09-04',time:'10:30',status:'مؤكد'},{id:'a2',patient:'عمر خالد',doctor:'د. ليلى مراد',service:'فحص وتشخيص',date:'2026-09-04',time:'12:00',status:'بانتظار التأكيد'},{id:'a3',patient:'مريم علي',doctor:'د. أحمد سامي',service:'تقويم',date:'2026-09-05',time:'14:30',status:'مؤكد'}],
 patients:[{id:'p1',file:'OR-1001',name:'سارة محمد',phone:'+90 555 120 2244',birth:'1994-05-12',blood:'A+',allergy:'بنسلين',chronic:'لا يوجد',meds:'لا يوجد',contact:'محمد — +90 555 331 1122',balance:'1200'},{id:'p2',file:'OR-1002',name:'عمر خالد',phone:'+90 555 771 3900',birth:'1988-11-02',blood:'O+',allergy:'لا يوجد',chronic:'سكري',meds:'Metformin',contact:'نور — +90 555 992 7711',balance:'0'},{id:'p3',file:'OR-1003',name:'مريم علي',phone:'+90 555 100 4402',birth:'2002-07-21',blood:'B+',allergy:'لاتكس',chronic:'لا يوجد',meds:'لا يوجد',contact:'علي — +90 555 109 4401',balance:'450'}],
 sessions:[{id:'s1',patient:'سارة محمد',doctor:'د. أحمد سامي',date:'2026-09-01',procedure:'ترميم السن 16',visible:'تم تنظيف التسوس ووضع حشوة دائمة.',internal:'متابعة الإطباق في الزيارة القادمة',material:'كومبوزيت',qty:'1',status:'معتمدة'}],
 plans:[{id:'pl1',patient:'سارة محمد',title:'علاج وترميم',cost:'8500',paid:'3200',progress:'42',expiry:'2026-10-01',status:'نشطة'},{id:'pl2',patient:'مريم علي',title:'تقويم شفاف',cost:'24000',paid:'6000',progress:'25',expiry:'2026-10-15',status:'نشطة'}],
 prescriptions:[{id:'rx1',patient:'سارة محمد',doctor:'د. أحمد سامي',date:'2026-09-01',medicine:'Ibuprofen 400mg',dose:'بعد الأكل عند اللزوم',instructions:'لا تتجاوز 3 أقراص يوميًا'}],
 imaging:[{id:'im1',patient:'سارة محمد',type:'أشعة بانوراما',date:'2026-08-28',shared:'نعم',notes:'صورة تشخيصية أولية'},{id:'im2',patient:'عمر خالد',type:'أشعة موضعية',date:'2026-09-02',shared:'لا',notes:'للمراجعة الداخلية'}],
 finance:[{id:'f1',date:'2026-09-03',type:'دفعة',person:'سارة محمد',method:'بطاقة',amount:'1500',status:'معتمدة'},{id:'f2',date:'2026-09-03',type:'مصروف',person:'معمل الأمل',method:'تحويل',amount:'620',status:'معتمدة'}],
 inventory:[{id:'i1',item:'كومبوزيت',sku:'MAT-101',qty:'18',min:'5',unit:'عبوة',expiry:'2027-01-30'},{id:'i2',item:'قفازات',sku:'MAT-102',qty:'4',min:'8',unit:'صندوق',expiry:'2028-06-01'},{id:'i3',item:'مخدر موضعي',sku:'MAT-103',qty:'12',min:'4',unit:'علبة',expiry:'2026-11-20'}],
 labs:[{id:'l1',patient:'مريم علي',lab:'معمل الابتسامة',work:'قالب تقويم',sent:'2026-08-29',due:'2026-09-07',cost:'900',status:'قيد التنفيذ'}],
 staff:[{id:'u1',name:'أحمد سامي',role:'دكتور',phone:'+90 555 444 1010',shift:'09:00–17:00',status:'نشط',permission:'الدكتور'},{id:'u2',name:'ليلى مراد',role:'دكتورة',phone:'+90 555 444 2020',shift:'11:00–19:00',status:'نشط',permission:'الدكتور'},{id:'u3',name:'هدى علي',role:'استقبال',phone:'+90 555 444 3030',shift:'08:30–16:30',status:'نشط',permission:'موظف الاستقبال'}],
 messages:[{id:'m1',patient:'سارة محمد',topic:'موعد',subject:'تغيير موعد المتابعة',message:'هل يمكن نقل الموعد إلى الساعة 12؟',status:'جديدة'},{id:'m2',patient:'مريم علي',topic:'علاج',subject:'تعليمات التقويم',message:'أحتاج نسخة من التعليمات.',status:'تم الرد'}],
 teeth:Object.fromEntries(Array.from({length:32},(_,i)=>[i+1,{status:i===5?'caries':i===12?'treated':i===20?'missing':'healthy',note:''}])),
 settings:{clinic:'ORAVENA Dental',currency:'TRY',appointmentDuration:'30',lateMinutes:'15',planDays:'30',adultAge:'18',inventory:true,labs:true,insurance:false,doctorRates:false,rooms:true,notifications:true},
 notifications:[{id:'n1',title:'مخزون منخفض',text:'قفازات أقل من الحد الأدنى.',read:false},{id:'n2',title:'طلب موعد جديد',text:'يوجد طلب موعد بانتظار التأكيد.',read:false}],
 audit:[{id:'log1',date:now(),user:'النظام',action:'تهيئة النسخة التجريبية',details:'تم تحميل بيانات آمنة للاختبار'}]
});
let db; try{db=JSON.parse(localStorage.getItem(KEY))||seed()}catch{db=seed()} let role=new URLSearchParams(location.search).get('role')||localStorage.getItem('oravenaRole')||'admin', section='dashboard', editing=null, filter='';
const save=()=>localStorage.setItem(KEY,JSON.stringify(db)); save();
const log=(action,details='')=>{db.audit.unshift({id:uid(),date:now(),user:roleName(),action,details});save()};
const roleName=()=>({admin:'المدير الرئيسي',doctor:'الدكتور',employee:'الموظف',patient:'المريض'})[role];
const defs={
 appointments:{title:'المواعيد',icon:'◷',cols:{patient:'المريض',doctor:'الدكتور',service:'الخدمة',date:'التاريخ',time:'الوقت',status:'الحالة'},fields:[['patient','المريض','selectPatient'],['doctor','الدكتور','text'],['service','الخدمة','text'],['date','التاريخ','date'],['time','الوقت','time'],['status','الحالة','select','مؤكد|بانتظار التأكيد|ملغي|مكتمل']]},
 patients:{title:'المرضى',icon:'♙',cols:{file:'رقم الملف',name:'الاسم',phone:'الهاتف',birth:'تاريخ الميلاد',allergy:'الحساسية',balance:'الرصيد'},fields:[['file','رقم الملف','text'],['name','الاسم','text'],['phone','الهاتف','tel'],['birth','تاريخ الميلاد','date'],['blood','فصيلة الدم','text'],['allergy','الحساسية','text'],['chronic','الأمراض المزمنة','text'],['meds','الأدوية الحالية','text'],['contact','اتصال الطوارئ','text'],['balance','الرصيد','number']]},
 sessions:{title:'الجلسات',icon:'✚',cols:{patient:'المريض',doctor:'الدكتور',date:'التاريخ',procedure:'الإجراء',status:'الحالة'},fields:[['patient','المريض','selectPatient'],['doctor','الدكتور','text'],['date','التاريخ','date'],['procedure','الإجراء','text'],['visible','ملخص يظهر للمريض','textarea'],['internal','ملاحظات داخلية','textarea'],['material','المادة المستخدمة','selectInventory'],['qty','الكمية','number'],['status','الحالة','select','مسودة|معتمدة']]},
 plans:{title:'خطط العلاج',icon:'▤',cols:{patient:'المريض',title:'الخطة',cost:'التكلفة',paid:'المدفوع',progress:'التقدم %',status:'الحالة'},fields:[['patient','المريض','selectPatient'],['title','اسم الخطة','text'],['cost','التكلفة','number'],['paid','المدفوع','number'],['progress','التقدم %','number'],['expiry','الصلاحية حتى','date'],['status','الحالة','select','مسودة|نشطة|مكتملة|ملغاة']]},
 prescriptions:{title:'الوصفات',icon:'℞',cols:{patient:'المريض',doctor:'الدكتور',date:'التاريخ',medicine:'الدواء',dose:'الجرعة'},fields:[['patient','المريض','selectPatient'],['doctor','الدكتور','text'],['date','التاريخ','date'],['medicine','الدواء','text'],['dose','الجرعة','text'],['instructions','التعليمات','textarea']]},
 imaging:{title:'الصور والأشعة',icon:'◉',cols:{patient:'المريض',type:'النوع',date:'التاريخ',shared:'يظهر للمريض',notes:'الملاحظات'},fields:[['patient','المريض','selectPatient'],['type','نوع الملف','text'],['date','التاريخ','date'],['shared','مشاركة مع المريض','select','نعم|لا'],['notes','الملاحظات','textarea']]},
 finance:{title:'الحسابات والمالية',icon:'₺',cols:{date:'التاريخ',type:'النوع',person:'المريض / الجهة',method:'الطريقة',amount:'القيمة',status:'الحالة'},fields:[['date','التاريخ','date'],['type','نوع الحركة','select','دفعة|مصروف|تحويل رصيد|استرداد'],['person','المريض / الجهة','text'],['method','طريقة الدفع','select','نقدي|بطاقة|تحويل'],['amount','القيمة','number'],['status','الحالة','select','مسودة|معتمدة|بانتظار المزامنة']]},
 inventory:{title:'المخزون',icon:'▣',cols:{item:'المادة',sku:'الكود',qty:'الكمية',min:'حد التنبيه',unit:'الوحدة',expiry:'الصلاحية'},fields:[['item','اسم المادة','text'],['sku','الكود','text'],['qty','الكمية','number'],['min','حد التنبيه','number'],['unit','الوحدة','text'],['expiry','تاريخ الصلاحية','date']]},
 labs:{title:'المعامل الخارجية',icon:'⚗',cols:{patient:'المريض',lab:'المعمل',work:'العمل',sent:'الإرسال',due:'التسليم',cost:'التكلفة',status:'الحالة'},fields:[['patient','المريض','selectPatient'],['lab','اسم المعمل','text'],['work','العمل المطلوب','text'],['sent','تاريخ الإرسال','date'],['due','موعد التسليم','date'],['cost','التكلفة','number'],['status','الحالة','select','قيد التنفيذ|وصل|مرفوض|تم التسليم']]},
 staff:{title:'الموظفون والصلاحيات',icon:'♟',cols:{name:'الاسم',role:'المسمى',phone:'الهاتف',shift:'الوردية',status:'الحساب',permission:'قالب الصلاحية'},fields:[['name','الاسم','text'],['role','المسمى الوظيفي','text'],['phone','الهاتف','tel'],['shift','الوردية','text'],['status','الحالة','select','نشط|موقوف'],['permission','قالب الصلاحية','select','الدكتور|الممرضة|موظف الاستقبال|المحاسب|مسؤول المخزون|مخصص']]},
 messages:{title:'الرسائل والطلبات',icon:'✉',cols:{patient:'المريض',topic:'الموضوع',subject:'العنوان',message:'الرسالة',status:'الحالة'},fields:[['patient','المريض','selectPatient'],['topic','نوع الموضوع','select','موعد|علاج|حساب|ملف'],['subject','العنوان','text'],['message','الرسالة','textarea'],['status','الحالة','select','جديدة|قيد المتابعة|تم الرد']]}
};
const menus={admin:['dashboard','appointments','patients','sessions','odontogram','plans','prescriptions','imaging','finance','inventory','labs','staff','messages','reports','audit','settings'],doctor:['dashboard','appointments','patients','sessions','odontogram','plans','prescriptions','imaging','messages'],employee:['dashboard','appointments','patients','finance','inventory','labs','messages'],patient:['dashboard','appointments','odontogram','plans','prescriptions','imaging','messages']};
const special={dashboard:['لوحة المتابعة','⌂'],odontogram:['خريطة الأسنان','◌'],reports:['التقارير','▥'],audit:['سجل الأمان','⌁'],settings:['الإعدادات','⚙']};
function nav(){if(!menus[role].includes(section))section='dashboard'; $('#sideNav').innerHTML=menus[role].map(k=>`<button class="nav-btn ${k===section?'active':''}" data-section="${k}"><i>${special[k]?.[1]||defs[k].icon}</i>${special[k]?.[0]||defs[k].title}</button>`).join('');document.querySelectorAll('[data-section]').forEach(b=>b.onclick=()=>{section=b.dataset.section;filter='';$('#globalSearch').value='';render()})}
function stat(label,value,note=''){return `<div class="stat"><small>${label}</small><strong>${esc(value)}</strong><span>${esc(note)}</span></div>`}
function dashboard(){let income=db.finance.filter(x=>x.type==='دفعة').reduce((a,x)=>a+(+x.amount||0),0), expenses=db.finance.filter(x=>x.type==='مصروف').reduce((a,x)=>a+(+x.amount||0),0);if(role==='patient')return `<div class="notice patient-switch">أنت تشاهد ملف <select id="familySwitch"><option>سارة محمد</option><option>آدم محمد — طفل</option></select> — رقم الملف OR-1001</div><div class="stats">${stat('الموعد القادم','4 سبتمبر','10:30')}${stat('تقدم الخطة','42%','علاج وترميم')}${stat('الرصيد المتبقي','5,300 ₺','آخر دفعة 1,500 ₺')}${stat('الملفات المتاحة','3','تنزيل بتحقق إضافي')}</div><div class="grid-2"><div class="panel"><div class="panel-head"><h2>الخطة النشطة</h2><span class="badge ok">معتمدة</span></div><h3>علاج وترميم</h3><p class="muted">تم إنجاز 3 من 7 إجراءات</p><div class="progress-bar"><i style="width:42%"></i></div><div class="quick-actions" style="margin-top:18px"><button data-go="appointments">طلب موعد</button><button data-go="messages">إرسال طلب للعيادة</button><button id="downloadFiles">تنزيل ملفاتي المسموح بها</button><button data-go="odontogram">عرض خريطة الأسنان</button></div></div><div class="panel"><h2>آخر ملخص جلسة</h2><p>تم تنظيف التسوس ووضع حشوة دائمة.</p><p class="muted">الملاحظات الداخلية مخفية وفق صلاحيات المريض.</p></div></div>`;
 return `<div class="stats">${stat('مواعيد اليوم',db.appointments.filter(x=>x.date==='2026-09-04').length,'منها طلب ينتظر التأكيد')}${stat('المرضى',db.patients.length,'ملفات نشطة')}${stat('إيرادات مسجلة',income.toLocaleString()+' ₺','داخل النسخة المحلية')}${stat('تنبيهات المخزون',db.inventory.filter(x=>+x.qty<=+x.min).length,'تحتاج مراجعة')}</div><div class="grid-2"><div class="panel"><div class="panel-head"><h2>مواعيد قريبة</h2><button class="mini" data-go="appointments">عرض الكل</button></div>${table('appointments',db.appointments.slice(0,4),false)}</div><div class="panel"><h2>إجراءات سريعة</h2><div class="quick-actions"><button data-new="appointments">＋ موعد</button><button data-new="patients">＋ مريض</button><button data-new="sessions">＋ جلسة</button><button data-new="finance">＋ حركة مالية</button></div><h3 style="margin-top:22px">آخر النشاطات</h3><ul class="activity">${db.audit.slice(0,4).map(x=>`<li><b>${esc(x.action)}</b><small>${esc(x.date)} · ${esc(x.user)}</small></li>`).join('')}</ul></div></div><div class="panel"><div class="panel-head"><h2>ملخص اليوم</h2><span class="muted">المصروفات ${expenses.toLocaleString()} ₺</span></div><div class="report-bars"><div class="report-row"><span>المواعيد</span><div><i style="width:78%"></i></div><b>${db.appointments.length}</b></div><div class="report-row"><span>الجلسات</span><div><i style="width:55%"></i></div><b>${db.sessions.length}</b></div><div class="report-row"><span>التحصيل</span><div><i style="width:66%"></i></div><b>${income}</b></div></div></div>`}
function visibleRows(k){let rows=db[k]||[];if(role==='patient')rows=rows.filter(x=>!x.patient||x.patient==='سارة محمد').map(x=>k==='sessions'?(({internal,...r})=>r)(x):x);if(filter){let f=filter.toLowerCase();rows=rows.filter(x=>Object.values(x).some(v=>String(v).toLowerCase().includes(f)))}return rows}
function table(k,rows=visibleRows(k),actions=true){let d=defs[k];if(!rows.length)return '<div class="empty"><b>⌕</b>لا توجد سجلات مطابقة</div>';let cols=Object.entries(d.cols);return `<div class="table-wrap"><table class="data-table"><thead><tr>${cols.map(([,v])=>`<th>${v}</th>`).join('')}${actions&&role!=='patient'?'<th>الإجراءات</th>':''}</tr></thead><tbody>${rows.map(r=>`<tr>${cols.map(([c])=>`<td>${c==='status'?`<span class="badge ${String(r[c]).includes('ملغ')?'danger':String(r[c]).includes('انتظار')||String(r[c]).includes('تنفيذ')?'warn':'ok'}">${esc(r[c])}</span>`:esc(r[c])}</td>`).join('')}${actions&&role!=='patient'?`<td><div class="row-actions"><button class="mini edit" data-edit="${k}:${r.id}">تعديل</button><button class="mini delete" data-delete="${k}:${r.id}">حذف</button>${k==='finance'&&r.type==='دفعة'?`<button class="mini refund" data-refund="${r.id}">استرداد</button>`:''}</div></td>`:''}</tr>`).join('')}</tbody></table></div>`}
function listPage(k){let extra=k==='finance'?`<div class="stats">${stat('إجمالي الدفعات',db.finance.filter(x=>x.type==='دفعة').reduce((a,x)=>a+(+x.amount||0),0)+' ₺')}${stat('إجمالي المصروفات',db.finance.filter(x=>x.type==='مصروف').reduce((a,x)=>a+(+x.amount||0),0)+' ₺')}${stat('صافي الحركة',db.finance.reduce((a,x)=>a+(x.type==='دفعة'?+x.amount:-(+x.amount)),0)+' ₺')}${stat('العملة',db.settings.currency)}</div>`:'';return extra+`<div class="panel"><div class="panel-head"><h2>${defs[k].title}</h2><span class="muted">${visibleRows(k).length} سجل</span></div>${table(k)}</div>`}
function odontogram(){return `<div class="grid-2"><div class="odontogram"><div class="jaw">${Array.from({length:16},(_,i)=>tooth(i+1)).join('')}</div><div class="jaw lower">${Array.from({length:16},(_,i)=>tooth(i+17)).join('')}</div><div class="legend"><span><i style="background:#fff;border:1px solid #aaa"></i>سليم</span><span><i style="background:#e99032"></i>تسوس</span><span><i style="background:#18b7ad"></i>معالج</span><span><i style="background:#aaa"></i>مفقود/زراعة</span><span><i style="background:#d64545"></i>مخطط</span></div></div><div class="panel"><h2>خريطة 32 سنًا</h2><p class="muted">اضغط على أي سن لتغيير حالته وإضافة ملاحظة. التغيير يُحفظ فورًا داخل المتصفح.</p><ul class="activity">${Object.entries(db.teeth).filter(([,v])=>v.status!=='healthy').map(([n,v])=>`<li><b>السن ${n} — ${statusName(v.status)}</b><small>${esc(v.note||'لا توجد ملاحظة')}</small></li>`).join('')||'<li>كل الأسنان مسجلة سليمة.</li>'}</ul></div></div>`}
function tooth(n){let s=db.teeth[n]?.status||'healthy';return `<button class="tooth ${s}" data-tooth="${n}" title="السن ${n}: ${statusName(s)}">${n}</button>`}function statusName(s){return({healthy:'سليم',caries:'تسوس',treated:'معالج',missing:'مفقود',implant:'زراعة',planned:'إجراء مخطط'})[s]}
function reports(){let inc=db.finance.filter(x=>x.type==='دفعة').reduce((a,x)=>a+(+x.amount||0),0);return `<div class="stats">${stat('التحصيل',inc+' ₺')}${stat('الجلسات المكتملة',db.sessions.length)}${stat('خطط نشطة',db.plans.filter(x=>x.status==='نشطة').length)}${stat('حالات معمل',db.labs.length)}</div><div class="grid-2"><div class="panel"><h2>مؤشرات التشغيل</h2><div class="report-bars">${[['الحجوزات',82],['الحضور',71],['إنجاز الخطط',56],['التحصيل',68]].map(x=>`<div class="report-row"><span>${x[0]}</span><div><i style="width:${x[1]}%"></i></div><b>${x[1]}%</b></div>`).join('')}</div></div><div class="panel"><h2>تصدير التقرير</h2><p class="muted">يمكن تصدير كل بيانات النسخة المحلية بصيغة JSON واستعادتها لاحقًا.</p><button class="primary" id="reportExport">تصدير الآن</button></div></div>`}
function audit(){return `<div class="panel"><div class="panel-head"><h2>سجل غير قابل للتعديل من الواجهة</h2><span class="badge">${db.audit.length} عملية</span></div><div class="table-wrap"><table class="data-table"><thead><tr><th>التاريخ</th><th>المستخدم</th><th>العملية</th><th>التفاصيل</th></tr></thead><tbody>${db.audit.map(x=>`<tr><td>${esc(x.date)}</td><td>${esc(x.user)}</td><td>${esc(x.action)}</td><td>${esc(x.details)}</td></tr>`).join('')}</tbody></table></div></div>`}
function settings(){return `<div class="grid-2"><div class="panel"><h2>الإعدادات العامة</h2><div class="form-grid" id="settingsForm"><label>اسم العيادة<input data-setting="clinic" value="${esc(db.settings.clinic)}"></label><label>العملة<select data-setting="currency"><option ${db.settings.currency==='TRY'?'selected':''}>TRY</option><option>USD</option><option>EUR</option></select></label><label>مدة الموعد بالدقائق<input type="number" data-setting="appointmentDuration" value="${esc(db.settings.appointmentDuration)}"></label><label>مهلة التأخير<input type="number" data-setting="lateMinutes" value="${esc(db.settings.lateMinutes)}"></label><label>صلاحية الخطة بالأيام<input type="number" data-setting="planDays" value="${esc(db.settings.planDays)}"></label><label>سن استقلال حساب الطفل<input type="number" data-setting="adultAge" value="${esc(db.settings.adultAge)}"></label></div><button class="primary" id="saveSettings" style="margin-top:16px">حفظ الإعدادات</button></div><div class="panel"><h2>الوحدات الاختيارية</h2><div class="settings-grid">${[['inventory','المخزون'],['labs','المعامل'],['insurance','التأمين'],['doctorRates','نسب الأطباء'],['rooms','الغرف والكراسي'],['notifications','الإشعارات']].map(([k,l])=>`<div class="setting"><span>${l}</span><button class="switch ${db.settings[k]?'on':''}" data-toggle="${k}"><i></i></button></div>`).join('')}</div></div></div><div class="panel danger-zone"><h2>بيانات النسخة التجريبية</h2><p class="muted">التصفير يعيد المرضى والمواعيد والحركات الوهمية إلى الحالة الأصلية. يمكنك التصدير أولًا.</p><div class="toolbar"><button class="secondary" id="importButton">استيراد نسخة</button><button class="secondary" id="settingsExport">تصدير نسخة</button><button class="danger-btn" id="resetDemo">تصفير البيانات التجريبية</button></div></div>`}
function render(){nav();$('#roleSelect').value=role;let title=special[section]?.[0]||defs[section]?.title||'';$('#pageTitle').textContent=title;$('#pageKicker').textContent=roleName();let canAdd=defs[section]&&!(role==='patient'&&!['appointments','messages'].includes(section));$('#primaryAction').hidden=!canAdd;$('#primaryAction').textContent=section==='messages'?'رسالة جديدة':'إضافة جديد';$('#globalSearch').disabled=!defs[section];let html=section==='dashboard'?dashboard():section==='odontogram'?odontogram():section==='reports'?reports():section==='audit'?audit():section==='settings'?settings():listPage(section);$('#content').innerHTML=html;wire();updateNotifications()}
function wire(){document.querySelectorAll('[data-go]').forEach(b=>b.onclick=()=>{section=b.dataset.go;render()});document.querySelectorAll('[data-new]').forEach(b=>b.onclick=()=>openEditor(b.dataset.new));document.querySelectorAll('[data-edit]').forEach(b=>b.onclick=()=>{let[k,id]=b.dataset.edit.split(':');openEditor(k,id)});document.querySelectorAll('[data-delete]').forEach(b=>b.onclick=()=>remove(...b.dataset.delete.split(':')));document.querySelectorAll('[data-refund]').forEach(b=>b.onclick=()=>refund(b.dataset.refund));document.querySelectorAll('[data-tooth]').forEach(b=>b.onclick=()=>openTooth(b.dataset.tooth));document.querySelectorAll('[data-toggle]').forEach(b=>b.onclick=()=>{let k=b.dataset.toggle;db.settings[k]=!db.settings[k];log('تغيير وحدة',`${k}: ${db.settings[k]?'مفعلة':'معطلة'}`);render()});$('#saveSettings')?.addEventListener('click',()=>{document.querySelectorAll('[data-setting]').forEach(i=>db.settings[i.dataset.setting]=i.value);log('تحديث الإعدادات','تم حفظ الإعدادات العامة');toast('تم حفظ الإعدادات')});$('#resetDemo')?.addEventListener('click',()=>{if(confirm('هل تريد تصفير بيانات التشغيل التجريبية؟')){db=seed();save();render();toast('تمت إعادة البيانات التجريبية')}});$('#importButton')?.addEventListener('click',()=>$('#importInput').click());$('#settingsExport')?.addEventListener('click',exportData);$('#reportExport')?.addEventListener('click',exportData);$('#downloadFiles')?.addEventListener('click',()=>{let code=prompt('للتحقق الإضافي اكتب 1234');if(code==='1234'){log('تنزيل ملفات المريض','تنزيل الملفات المسموح بها');download('oravena-patient-files.txt','ملف ORAVENA للمريض\nالخطة: علاج وترميم\nآخر جلسة: تم تنظيف التسوس ووضع حشوة دائمة.');toast('تم تنزيل الملفات وتسجيل العملية')}else if(code!==null)toast('رمز التحقق غير صحيح')})}
function inputFor([k,l,t,opts],v=''){let input=t==='textarea'?`<textarea name="${k}" rows="3">${esc(v)}</textarea>`:t==='select'?`<select name="${k}">${opts.split('|').map(o=>`<option ${v===o?'selected':''}>${o}</option>`).join('')}</select>`:t==='selectPatient'?`<select name="${k}">${db.patients.map(p=>`<option ${v===p.name?'selected':''}>${esc(p.name)}</option>`).join('')}</select>`:t==='selectInventory'?`<select name="${k}"><option value="">بدون مادة</option>${db.inventory.map(p=>`<option ${v===p.item?'selected':''}>${esc(p.item)}</option>`).join('')}</select>`:`<input name="${k}" type="${t}" value="${esc(v)}" ${['number'].includes(t)?'min="0"':''} required>`;return `<label class="${t==='textarea'?'wide':''}">${l}${input}</label>`}
function openEditor(k,id=null){editing={k,id};let d=defs[k], rec=id?db[k].find(x=>x.id===id):{};$('#editorTitle').textContent=(id?'تعديل ':'إضافة ')+d.title;$('#editorFields').innerHTML=d.fields.map(f=>inputFor(f,rec[f[0]])).join('');$('#editorDialog').showModal()}
$('#editorForm').onsubmit=e=>{e.preventDefault();let data=Object.fromEntries(new FormData(e.currentTarget)), {k,id}=editing;if(k==='finance'&&data.type==='استرداد'&&!navigator.onLine){toast('لا يمكن الاسترداد أثناء انقطاع الإنترنت');return}if(id){Object.assign(db[k].find(x=>x.id===id),data);log('تعديل '+defs[k].title,data.patient||data.name||data.item||id)}else{db[k].unshift({id:uid(),...data});log('إضافة '+defs[k].title,data.patient||data.name||data.item||'سجل جديد')}if(k==='sessions'&&data.material&&+data.qty){let item=db.inventory.find(x=>x.item===data.material);if(item)item.qty=String(Math.max(0,+item.qty-(+data.qty)))}save();$('#editorDialog').close();render();toast('تم الحفظ بنجاح')};
function remove(k,id){if(!confirm('هل تريد حذف هذا السجل؟'))return;let r=db[k].find(x=>x.id===id);db[k]=db[k].filter(x=>x.id!==id);log('حذف '+defs[k].title,r?.name||r?.patient||r?.item||id);render();toast('تم الحذف')}
function refund(id){if(!navigator.onLine){toast('الاسترداد متوقف أثناء العمل دون إنترنت');return}let r=db.finance.find(x=>x.id===id);if(confirm(`تسجيل استرداد بقيمة ${r.amount}؟`)){db.finance.unshift({...r,id:uid(),date:new Date().toISOString().slice(0,10),type:'استرداد',amount:r.amount,status:'معتمدة'});log('استرداد دفعة',r.person);render()}}
function openTooth(n){$('#toothId').value=n;$('#toothNumber').textContent=n;$('#toothStatus').value=db.teeth[n].status;$('#toothNote').value=db.teeth[n].note;$('#toothDialog').showModal()}$('#toothForm').onsubmit=e=>{e.preventDefault();let n=$('#toothId').value;db.teeth[n]={status:$('#toothStatus').value,note:$('#toothNote').value};log('تحديث خريطة الأسنان',`السن ${n}: ${statusName(db.teeth[n].status)}`);$('#toothDialog').close();render();toast('تم تحديث السن')};
function download(name,text){let a=document.createElement('a');a.href=URL.createObjectURL(new Blob([text],{type:'application/octet-stream'}));a.download=name;a.click();URL.revokeObjectURL(a.href)}function exportData(){log('تصدير نسخة احتياطية','JSON');download('oravena-demo-backup.json',JSON.stringify(db,null,2));toast('تم تصدير النسخة')}
$('#importInput').onchange=e=>{let f=e.target.files[0];if(!f)return;let r=new FileReader;r.onload=()=>{try{let x=JSON.parse(r.result);if(!x.patients||!x.settings)throw Error();db=x;log('استيراد نسخة احتياطية',f.name);render();toast('تم الاستيراد بنجاح')}catch{toast('الملف غير صالح')}};r.readAsText(f);e.target.value=''};
function updateNotifications(){let n=db.notifications.filter(x=>!x.read).length;$('#notificationCount').textContent=n;$('#notificationCount').hidden=!n;$('#notificationsList').innerHTML=db.notifications.map(x=>`<div class="notifications-item ${x.read?'':'unread'}"><strong>${esc(x.title)}</strong><p>${esc(x.text)}</p></div>`).join('')}
$('#notificationsButton').onclick=()=>{$('#notificationsDialog').showModal()};$('#readAllButton').onclick=()=>{db.notifications.forEach(x=>x.read=true);save();updateNotifications();toast('تمت قراءة التنبيهات')};
$('#emergencyButton').onclick=()=>{let p=db.patients[0];$('#emergencyContent').innerHTML=`<div class="emergency-data"><div><small>المريض</small>${esc(p.name)}</div><div><small>رقم الملف</small>${esc(p.file)}</div><div><small>فصيلة الدم</small>${esc(p.blood)}</div><div><small>الحساسية</small>${esc(p.allergy)}</div><div><small>أمراض مزمنة</small>${esc(p.chronic)}</div><div><small>الأدوية الحالية</small>${esc(p.meds)}</div><div><small>آخر وصفة</small>${esc(db.prescriptions[0]?.medicine)}</div><div><small>اتصال الطوارئ</small>${esc(p.contact)}</div></div>`;$('#emergencyDialog').showModal()};$('#recordEmergencyButton').onclick=()=>{let reason=prompt('اكتب سبب الوصول الطبي الطارئ');if(reason){log('وصول طبي طارئ',reason);$('#emergencyDialog').close();toast('تم تسجيل السبب وإخطار المدير')}};
$('#primaryAction').onclick=()=>openEditor(section);$('#exportButton').onclick=exportData;$('#roleSelect').onchange=e=>{role=e.target.value;localStorage.setItem('oravenaRole',role);section='dashboard';render();toast('تم التبديل إلى '+roleName())};$('#globalSearch').oninput=e=>{filter=e.target.value;render()};$('#sideToggle').onclick=()=>$('#side').classList.toggle('open');document.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>document.getElementById(b.dataset.close).close());
function connection(){let off=!navigator.onLine;$('#connection').classList.toggle('offline',off);$('#connection span').textContent=off?'غير متصل — الحفظ محلي':'متصل — الحفظ محلي'}addEventListener('online',connection);addEventListener('offline',connection);connection();let toastTimer;function toast(s){$('#toast').textContent=s;$('#toast').classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').classList.remove('show'),2600)}render();
